# Generated by Django 4.2.16 on 2024-12-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('ID_Specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.specialization')),
            ],
            options={
                'db_table': 'Commission',
            },
        ),
        migrations.CreateModel(
            name='CommissionMember',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Surname', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Patronymic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CommissionMember',
            },
        ),
        migrations.CreateModel(
            name='DefenseSchedule',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField()),
                ('ID_Commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.commission')),
                ('Count', models.IntegerField()),
                ('Class', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'DefenseSchedule',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField(unique=True)),
                ('Supervisor', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=30)),
                ('Text', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(unique=True)),
                ('Qualification', models.TextField(unique=True)),
                ('Number', models.CharField(max_length=10)),
                ('Status', models.BooleanField()),
            ],
            options={
                'db_table': 'Specialization',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Surname', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Patronymic', models.CharField(max_length=50)),
                ('ID_Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.group')),
                ('ID_Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.project')),
                ('ID_Specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.specialization')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('ID_Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.project')),
                ('Status', models.BooleanField()),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Grade', models.CharField(max_length=30)),
                ('ID_DefenseSchedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.defenseschedule')),
                ('ID_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_set', to='audio.question')),
                ('ID_Question2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_set_2', to='audio.question')),
                ('ID_Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.student')),
                ('DefenseStartTime', models.TimeField(blank=True, null=True)),
                ('DefenseEndTime', models.TimeField(blank=True, null=True)),
                ('Number', models.CharField(max_length=30)),
                ('Status', models.BooleanField()), 
            ],
            options={
                'db_table': 'Protocol',
            },
        ),
        migrations.CreateModel(
            name='CommissionComposition',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=100)),
                ('ID_Commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.commission')),
                ('ID_Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.commissionmember')),
            ],
            options={
                'db_table': 'CommissionComposition',
            },
        ),
        migrations.CreateModel(
            name='SecretarySpecialization',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ID_Secretary',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.commissionmember')),
                ('ID_Specialization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.specialization')),
            ],
            options={
                'db_table': 'Secretary/Specialization',
            },
        ),
    ]
