# Generated by Django 5.2.11 on 2026-02-12 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defenseschedule',
            name='ID_Commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.commission'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='Grade',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
