# Generated by Django 5.2.11 on 2026-03-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_defenseschedule_id_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenseschedule',
            name='ID_Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.specialization'),
        ),
    ]
