# Generated by Django 5.2.13 on 2026-04-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_defenseschedule_id_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionmember',
            options={'verbose_name': 'Член комиссии', 'verbose_name_plural': 'Члены комиссии'},
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='login',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
